// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for the web platform - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtClzntLJpHiNge8GENFFZ32rWGryvZ1U',
    appId: '1:268984052456:android:2df3995ca552fc2f9f775d',
    messagingSenderId: '268984052456',
    projectId: 'asgardeo-react-native-sample',
    storageBucket: 'asgardeo-react-native-sample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzD-p5KD_P5-M74fm_0xgOLjDNHkBr2-U',
    appId: '1:268984052456:ios:0307c38f994e49f49f775d',
    messagingSenderId: '268984052456',
    projectId: 'asgardeo-react-native-sample',
    storageBucket: 'asgardeo-react-native-sample.firebasestorage.app',
    iosBundleId: 'io.asgardeo.dev.push.totp.authenticator',
  );

}